/* Gera uma demonstração legendada com capturas reais do dashboard.
   Requer navegador de teste isolado com CDP na porta 9335 e Node >= 22. */
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));

(async () => {
  const pages = await (await fetch('http://127.0.0.1:9335/json')).json();
  const ws = new WebSocket(pages.find(page => page.type === 'page').webSocketDebuggerUrl);
  await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
  let id = 0;
  const pending = new Map();
  ws.addEventListener('message', event => { const response = JSON.parse(event.data); if (pending.has(response.id)) { const task = pending.get(response.id); pending.delete(response.id); response.error ? task.reject(new Error(JSON.stringify(response.error))) : task.resolve(response.result); } });
  const call = (method, params = {}) => new Promise((resolve, reject) => { const requestId = ++id; pending.set(requestId, { resolve, reject }); ws.send(JSON.stringify({ id: requestId, method, params })); });
  const evaluate = async expression => { const response = await call('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (response.exceptionDetails) throw new Error(JSON.stringify(response.exceptionDetails)); return response.result.value; };
  const viewport = (width, height) => call('Emulation.setDeviceMetricsOverride', { width, height, deviceScaleFactor: 1, mobile: false });
  const snapshots = [];
  const capture = async (title, subtitle) => { await pause(650); const shot = await call('Page.captureScreenshot', {format:'png'}); snapshots.push({src:'data:image/png;base64,' + shot.data, title, subtitle}); console.log('Captura: ' + title); return shot.data; };
  const scroll = id => evaluate(`window.scrollTo({top:document.getElementById(${JSON.stringify(id)}).getBoundingClientRect().top+scrollY-20,behavior:'instant'})`);
  await call('Page.enable');
  await viewport(1440, 1000);
  await call('Page.navigate', {url:pathToFileURL(path.join(root, 'index.html')).href});
  await pause(1400);
  await evaluate(`document.getElementById('restore-original').click();document.getElementById('toast').hidden=true`);
  await capture('01 · Visão geral', '188 vendas · 670 itens · R$ 35.378,30 de receita. Seis indicadores, uma visão completa.');
  await evaluate(`document.getElementById('loja').value='Centro';document.getElementById('categoria').value='Ficção';document.getElementById('categoria').dispatchEvent(new Event('change'));window.scrollTo({top:490,behavior:'instant'})`);
  await capture('02 · Filtros combinados', 'Loja Centro + categoria Ficção: os indicadores, gráficos e vendas refletem a seleção.');
  await evaluate(`document.getElementById('clear-filters').click()`);
  await scroll('analises');
  await capture('03 · Quatro formas de analisar', 'Receita por categoria, participação, evolução mensal e cinco produtos mais vendidos.');
  await scroll('vendas');
  await evaluate(`document.querySelector('[data-sort="cents"]').click()`);
  await capture('04 · Vendas e exportação', 'As dez vendas mais recentes ordenadas por valor. Exporte toda a seleção em CSV.');
  await evaluate(`document.querySelector('[data-open-import]').click()`);
  await capture('05 · Atualização simples', 'Escolha ou arraste um CSV. O modelo e as instruções de preenchimento estão na mesma janela.');
  await evaluate(String.raw`(()=>{const t=new DataTransfer();t.items.add(new File(['Data,Loja\n2026-09-01,Centro'],'arquivo-invalido.csv',{type:'text/csv'}));const input=document.getElementById('csv-file');input.files=t.files;input.dispatchEvent(new Event('change'));})()`);
  await capture('06 · Validação antes de substituir', 'Um arquivo com colunas ausentes é rejeitado. A base atual permanece preservada.');
  await evaluate(String.raw`(()=>{const csv=window.BAHUBALI_INITIAL_CSV.trim()+'\n2026-09-01,Centro,Ficção,Novo capítulo,3,150.00\n';const t=new DataTransfer();t.items.add(new File([csv],'vendas_atualizadas.csv',{type:'text/csv'}));const input=document.getElementById('csv-file');input.files=t.files;input.dispatchEvent(new Event('change'));})()`);
  await capture('07 · Importação concluída', '189 registros importados. A nova base fica salva neste navegador quando permitido.');
  await evaluate(`document.getElementById('close-import').click();document.getElementById('toast').hidden=true;window.scrollTo({top:0,behavior:'instant'})`);
  await capture('08 · Um novo capítulo nos resultados', 'A venda de setembro atualiza período, receita, itens e comparação mensal automaticamente.');
  await evaluate(`document.querySelector('[data-open-import]').click();document.getElementById('restore-original').click()`);
  await capture('09 · Restauração em um clique', 'Volte à base fornecida sempre que precisar. Os filtros também são reiniciados.');
  await evaluate(`document.getElementById('close-import').click();document.getElementById('toast').hidden=true;window.scrollTo({top:0,behavior:'instant'})`);
  await viewport(390, 844);
  const mobile = await capture('10 · Seus dados também no celular', 'Layout responsivo, navegação por teclado e funcionamento sem internet.');
  fs.writeFileSync(path.join(__dirname, 'dashboard-mobile.png'), Buffer.from(mobile, 'base64'));
  await viewport(1440, 1000);
  await call('Page.navigate', {url:'about:blank'});
  await pause(300);
  console.log('Codificando vídeo de 45 segundos…');
  const encoded = await evaluate(`(async()=>{
    const scenes=${JSON.stringify(snapshots)};
    const images=await Promise.all(scenes.map(scene=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=scene.src})));
    const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=1080;document.body.append(canvas);
    const ctx=canvas.getContext('2d');const stream=canvas.captureStream(12);
    const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm;codecs=vp8';
    const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2800000});const chunks=[];
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
    const stopped=new Promise(resolve=>recorder.onstop=resolve);
    let start=performance.now();const duration=4500;let timer;
    const draw=()=>{const elapsed=performance.now()-start;const index=Math.min(scenes.length-1,Math.floor(elapsed/duration));const scene=scenes[index],img=images[index];
      ctx.fillStyle='#f6f7f2';ctx.fillRect(0,0,1440,1080);
      const scale=Math.min(1440/img.width,970/img.height);const width=img.width*scale,height=img.height*scale;ctx.drawImage(img,(1440-width)/2,0,width,height);
      ctx.fillStyle='#183f36';ctx.fillRect(0,974,1440,106);ctx.fillStyle='#ead8ac';ctx.font='bold 22px Segoe UI';ctx.fillText(scene.title,34,1010);
      ctx.fillStyle='#ffffff';ctx.font='17px Segoe UI';ctx.fillText(scene.subtitle,34,1046);
      ctx.fillStyle='#ccad70';ctx.fillRect(0,1075,1440*Math.min(1,elapsed/(scenes.length*duration)),5);
      if(elapsed>=scenes.length*duration){clearInterval(timer);recorder.stop();stream.getTracks().forEach(track=>track.stop())}
    };draw();recorder.start();timer=setInterval(draw,80);await stopped;
    const blob=new Blob(chunks,{type:'video/webm'});return await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(blob)});
  })()`);
  const videoPath = path.join(root, 'demonstracao-bahubali.webm');
  fs.writeFileSync(videoPath, Buffer.from(encoded, 'base64'));
  console.log(`Vídeo salvo: ${videoPath} (${fs.statSync(videoPath).size} bytes)`);
  await call('Browser.close');
  ws.close();
})().catch(error => { console.error(error); process.exit(1); });
